# DATABASE
DATABASE_CONFIG = {
}

# AIRLY
AIRLY_API_KEY = '-'

# FIELDS
FROM_DATE_TIME = 'fromDateTime'
TILL_DATE_TIME = 'tillDateTime'
NAME = 'name'
VALUE = 'value'
PM1 = 'PM1'
PM25 = 'PM25'
PM10 = 'PM10'
NO2 = 'NO2'
CO = 'CO'
PRESSURE = 'PRESSURE'
HUMIDITY = 'HUMIDITY'
TEMPERATURE = 'TEMPERATURE'
FROM_DATE = 'FROM_DATE'
TILL_DATE = 'TILL_DATE'
FROM_TIME = 'FROM_TIME'
TILL_TIME = 'TILL_TIME'
SENSOR_ID = 'SENSOR_ID'
VALUES = 'values'